#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6446055261                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Moving to Ireland: Expat Guide            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Moving to Ireland? Get the ultimate guide for a stress-free move! Our app provides info on housing, schools, healthcare & more. Download now!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                 
your_link                                 :                      
your_city                                 :                                 
email_address                             : support@movingtoireland.co
facebook_username                         :                                           
instagram_username                        : movingtoirelandapp
twitter_username                          : MovingIreland
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Step-by-step progress
    description                           : The app includes a checklist approach to make sure you will not miss any of the important point.
    fontawesome_icon_name                 : check
  
  - title                                 : Comprehensive content
    description                           : “Moving to Ireland” app has 170 book pages long content. All the information you'll need in one application.
    fontawesome_icon_name                 : book

  - title                                 : Personalized flow based on your profile
    description                           : Whether you're moving for work, study, or for a new adventure, “Moving to Ireland” is the perfect companion to make the most of your new life in Ireland.
    fontawesome_icon_name                 : user  

  - title                                 : Pre-move / Post-move
    description                           : You will find a special section, even if you're not arrived in Ireland yet.
    fontawesome_icon_name                 : suitcase  

  - title                                 : Tailored roadmap for your passport 
    description                           : Each citizenship has its journey while relocating. “Moving to Ireland” will guide on your way.
    fontawesome_icon_name                 : globe  

  - title                                 : Build your team
    description                           : “Moving to Ireland” provides all the required information not just yourself, but also for your spouse, kid(s) and even for pet(s).
    fontawesome_icon_name                 : users              

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#326CE6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#326CE6"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
